export const enum BlockObjectTypes {
    NEW_COLLECTION = 'newcollection',
    BANNER_CROSSROADS = 'banner-crossroads',
    PURE_TEXT = 'pure-text',
    SLIDER_PROGRESS_SLIDE = 'slider-progress-slide',
    SIMPLE = 'simple',
    SLIDER_SLIDE = 'slider-slide',
    URL_LINK = 'url-link',
    BANNER_PRIMARY = 'banner-primary',
    PRODUCT = 'product',
    BANNER = 'banner',
    BANNER_EXTENDED = 'banner-extended',
    BANNER_EXTENDED_NOBTN = 'banner-extended-nobtn',
    CATEGORY = 'category',
    CUSTOM = 'custom',
}
